name: MSP Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /services/msp-capstone-fe
            git fetch origin
            git checkout production
            git pull
            docker build -t msp-capstone-fe .
            docker stop msp-capstone-fe || true
            docker rm msp-capstone-fe || true
            docker run -d --name msp-capstone-fe -p 4000:3001 msp-capstone-fe
